### ISSUE TITLE
Crash when multiple functions are defined in serverless.yaml

### ISSUE THREAD

**Issue by iam4x** [threadheap/serverless-plugin-parcel#1]
Hi 👋 	

Thanks for the plugin, but I'm having an issue when multiple functions are defined into `serverless.yaml` for instance:

```yaml
functions:
  foo:
    handler: src/index.foo
    events:
      - http: POST foo
  bar:
    handler: src/index.bar
    events:
      - http: POST bar
```

> 🚨  Cannot add a worker call if workerfarm is ending.

Do you have any workaround? Cheers.
